sqlite 추가
Rainist/docker-python pull request #2
Opened 2019-12-09 10:24 UTC by AhnSeongHyun

```python 
import sqlite3
```

파이썬 기본 모듈 sqlite3 import 시의 오류해결을 위해서 sqlite-devel 를 추가합니다. 
python version 을 3.7.5 로 올립니다.

2019-12-09 10:50 UTC, Kcrong requested changes

2019-12-09 10:50 UTC, Kcrong commented on 3.7/centos7/Dockerfile
>      && yum clean all \
`python-devel`, `zlib-devel`, `ncurses-devel` 도 추가되면 좋을 것 같습니다. (모두 python 빌드 시 필요한 의존성 들입니다.)

참고) ubuntu 기준 필요 의존성 패키지들입니다.
- python-dev 
- libffi-dev 
- libssl-dev 
- zlib1g-dev 
- libncurses5-dev 
- libsqlite3-dev

2019-12-09 10:52 UTC, AhnSeongHyun commented on 3.7/centos7/Dockerfile
>      && yum clean all \
@Kcrong 위의 세개가 없으면 어떻게 되나요? 특정 모듈이 안되나요? 추가하더라도 테스트를
해봐야 할것 같아서요

2019-12-09 11:03 UTC, Kcrong commented on 3.7/centos7/Dockerfile
>      && yum clean all \
python3-dev는 기타 모듈을 설치할 때 필요한 C 헤더 파일을 담고 있는 패키지 입니다. python3-dev 가 설치되어 있지 않으면 몇몇 extension 들은 설치가 실패합니다. (python3-dev에 의존성을 가진 모듈 리스트가 있었는데.. 찾을 땐 또 없네요 ㅜ) 

여기 해당 패키지에 대한 설명이 있습니다.
https://stackoverflow.com/questions/31002091/what-is-python-dev-package-used-for

2019-12-09 11:03 UTC, Kcrong commented on 3.7/centos7/Dockerfile
>      && yum clean all \
zlib-devel 은 zlib, gzip에 의존성을 가진 패키지인데, `bzip2-devel` 에서 의존성 설치가 해결된 것으로 보입니다. 지금 도커 허브에 올라온 이미지로 테스트 해보니 잘 동작 하네요 👍 

ncurses-devel 은 curses 모듈에 대한 의존성 패키지입니다. 설치 시에 필요하며, 없을 경우 sqlite 와 같이 동일하게 ImportError 를 발생시킵니다.
![image](https://user-images.githubusercontent.com/13450715/70430795-e9646280-1abe-11ea-9f31-1e9ea8a74c3c.png)

2019-12-09 16:34 UTC, AhnSeongHyun commented on 3.7/centos7/Dockerfile
>      && yum clean all \
python3-dev 와 ncurses-deve 를 넣어서 알려주신 대로 테스트 해보고 잘 되면 추가하도록 하겠습니다. 🌮

2019-12-10 01:27 UTC, winterjung approved these changes
선 어프루브

2019-12-10 01:29 UTC, 0xd669 approved these changes
저도 우선은 LGTM. merge 이후 3.7.5 태그 따서 이미지 생성 부탁드립니다 🙏

2019-12-10 01:38 UTC, AhnSeongHyun commented
@Kcrong python3-devel, ncurses-devel 추가했습니다.

2019-12-10 02:48 UTC, Kcrong commented
처음과 변경사항이 달라진 관계로 본문 수정 부탁드립니다. 나머지는 LGTM

2019-12-10 03:03 UTC, merged